before_install: if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
    brew update;
  else
    sudo apt-get update -qq;
    sudo apt-get install -y cmake libxml2-dev libssl-dev;
  fi
script:
- mkdir build
- cd build
- cmake ..
- make

os:
 - linux
 - osx

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "AhDg868E2SgZbGhsFyDQd19IVCZcQ2a7shdojRTxIxF10TGhAleFEtm4EAoXjjgCPcGY52o1aVaEMea/GRnLR6oLQ592igxNHjTlTGKcDp5w28xVq9m7d4JVrvUeYvKoi+szS4Ah8zhraGdssMaq8LtZzLbaoEXCaMCDRlXPGro="

addons:
  coverity_scan:
    project:
      name: "open-eid/libdigidoc"
      description: "Build submitted via Travis CI"
    notification_email: raul@metsma.ee
    build_command_prepend: "mkdir coverity; cd coverity; cmake .."
    build_command: make
    branch_pattern: coverity_scan
